// back_whispers_3.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (69):
back_whispers.wad
barney.wad
CHANGELEVEL.wad
decals.wad
decay.wad
dmc.wad
gfx/env/cobblebk.tga
gfx/env/cobbledn.tga
gfx/env/cobbleft.tga
gfx/env/cobblelf.tga
gfx/env/cobblert.tga
gfx/env/cobbleup.tga
halflife.wad
liquids.wad
models/back_whsp/cars/2_cheap_delivery_truck_white.mdl
models/back_whsp/cars/2_euro_sedan_bluegrey.mdl
models/back_whsp/cars/2_humvee_camo.mdl
models/back_whsp/funitures/dirty_leather_couch_brown.mdl
models/back_whsp/funitures/wb_seat.mdl
models/back_whsp/others/electric_wire1.mdl
models/back_whsp/others/error.mdl
models/back_whsp/others/gonome.mdl
models/back_whsp/others/hgrunt.mdl
models/back_whsp/others/massn.mdl
models/back_whsp/others/shoes_s.mdl
models/osprey.mdl
op4ctf.wad
Opfor.wad
sound/ambience/des_wind2.wav
sound/ambience/des_wind3.wav
sound/ambience/distantmortar2.wav
sound/ambience/distantmortar3.wav
sound/ambience/fluorescent.wav
sound/ambience/water_flowing3.wav
sound/ambience/waterfall2.wav
sound/apache/ap_rotor4.wav
sound/back_whsp/ambient/ambientInsideWindRain.wav
sound/back_whsp/ambient/lv0br.wav
sound/back_whsp/ambient/pz_ambientOutsideRainWindThunder.wav
sound/back_whsp/music/Tpwt.wav
sound/back_whsp/time/10s_etqw.wav
sound/back_whsp/time/5s_etqw.wav
sound/back_whsp/voice/outro.wav
sound/buttons/bell1.wav
sound/buttons/button6.wav
sound/buttons/latchunlocked1.wav
sound/common/nuke_explode.wav
sound/debris/wood1.wav
sound/debris/wood2.wav
sound/debris/wood3.wav
sound/doors/doormove10.wav
sound/doors/doormove6.wav
sound/doors/doormove8.wav
sound/doors/doorstop6.wav
sound/doors/doorstop8.wav
sound/misc/secret.wav
sound/null.wav
sound/plats/squeekstop1.wav
sound/thunder.wav
sound/vox/access.wav
sound/vox/denied.wav
sprites/back_whsp/bw_ripples.spr
sprites/fire.spr
sprites/flare2.spr
sprites/laserbeam.spr
sprites/xsmoke1.spr
tfc.WAD
tfc2.wad
xeno.wad
