// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

borg.wad
dethtex_spacemadness.wad
gfx/env/toxic_bk.tga
gfx/env/toxic_dn.tga
gfx/env/toxic_ft.tga
gfx/env/toxic_lf.tga
gfx/env/toxic_rt.tga
gfx/env/toxic_up.tga
models/borgcube/9mmar/p_9mmar.mdl
models/borgcube/9mmar/v_9mmar.mdl
models/borgcube/9mmar/w_9mmar.mdl
models/borgcube/9mmar/w_chainammo.mdl
models/borgcube/borg/borg_controller.mdl
models/borgcube/borg/borg_gonome.mdl
models/borgcube/borg/borg_islave.mdl
models/borgcube/borg/borg_voltigore.mdl
models/borgcube/borg/borg_zombie.mdl
models/borgcube/borg/the_borgqueen.mdl
models/borgcube/dktag/p_crowbar.mdl
models/borgcube/dktag/v_crowbar.mdl
models/borgcube/dktag/w_crowbar.mdl
models/borgcube/grenade/p_grenade.mdl
models/borgcube/grenade/v_grenade.mdl
models/borgcube/grenade/w_grenade.mdl
models/borgcube/phaser/p_gauss.mdl
models/borgcube/phaser/v_phasergauss.mdl
models/borgcube/phaser/w_gauss.mdl
models/borgcube/w_miniborgcube.mdl
sb-slime.wad
sound/borgcube/borg/borg_alert2.ogg
sound/borgcube/borg/borg_alert3.ogg
sound/borgcube/borg/borg_alert4.ogg
sound/borgcube/borg/borg_alert5.ogg
sound/borgcube/borg/borg_alert6.ogg
sound/borgcube/borg/borg_alert7.ogg
sound/borgcube/borg/borg_alert8.ogg
sound/borgcube/borg/borg_beep.ogg
sound/borgcube/borg/borg_cover1.ogg
sound/borgcube/borg/borg_cover2.ogg
sound/borgcube/borg/borg_cover3.ogg
sound/borgcube/borg/borg_die1.ogg
sound/borgcube/borg/borg_hurt1.ogg
sound/borgcube/borg/borg_hurt2.ogg
sound/borgcube/borg/borg_hurt3.ogg
sound/borgcube/borg/borg_hurt4.ogg
sound/borgcube/borg/borg_idle2.ogg
sound/borgcube/borg/borg_idle3.ogg
sound/borgcube/borg/borg_idle4.ogg
sound/borgcube/borg/borg_idle5.ogg
sound/borgcube/borg/borg_idle6.ogg
sound/borgcube/borg/queendie.ogg
sound/Borgcube/lobby1.wav
sound/borgcube/matrix.wav
sound/borgcube/phaser/gauss2_phaser.ogg
sound/Borgcube/terminatorborg.wav
sound/weapons/CS/knife_draw.wav
sound/weapons/hg-deploy.wav
sound/weapons/hydra/activate.wav
sound/weapons/hydra/deploy.wav
sound/weapons/lmgg_bolt.wav
sound/weapons/lmgg_clipin.wav
sound/weapons/lmgg_clipout.wav
sprites/borgcube/dktag/640hud1.spr
sprites/borgcube/dktag/640hud4.spr
sprites/borgcube/lasspr.spr
sprites/borgcube/weapon_crowbar.txt
