// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

conundrum3.wad
gfx/env/anachronismbk.tga
gfx/env/anachronismdn.tga
gfx/env/anachronismft.tga
gfx/env/anachronismlf.tga
gfx/env/anachronismrt.tga
gfx/env/anachronismup.tga
maps/con3_materials.txt
models/con3/0penguin.mdl
models/con3/icebullsquid.mdl
models/con3/icedagon02.mdl
models/con3/icedagon2.mdl
models/con3/skeleton.mdl
models/con3/snowbarnacle.mdl
models/con3/snowdag02.mdl
models/con3/snowdagon2c.mdl
models/con3/snowhoundeye.mdl
models/con3/snowpit_drone2x.mdl
models/con3/tree35.mdl
sound/con3/avalanche.ogg
sound/con3/chilly_wind.ogg
sound/con3/creaks.ogg
sound/con3/dag_step1.ogg
sound/con3/dag_step1.wav
sound/con3/dag_step2.ogg
sound/con3/dag_step3.ogg
sound/con3/dag_step3.wav
sound/con3/dag_step4.ogg
sound/con3/hugewater.ogg
sound/con3/ice_cave.ogg
sound/con3/ice_crac.ogg
sound/con3/moverock.ogg
sound/con3/snowblow.ogg
sound/con3/w01.ogg
sound/con3/w02.ogg
sound/con3/w03.ogg
sound/con3/w04.ogg
sound/con3/zipup.ogg
sprites/con3/ballsmoke.spr
sprites/con3/skarispin.spr
