// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cl2.wad
sound/cl2/newsounds/ba1.wav
sound/cl2/newsounds/ba2.wav
sound/cl2/newsounds/ba3.wav
sound/cl2/newsounds/ba_escaped.wav
sound/cl2/newsounds/ba_escaped2.wav
sound/cl2/newsounds/baintro.wav
sound/cl2/newsounds/bameet.wav
sound/cl2/newsounds/bigsmoke/bs1.wav
sound/cl2/newsounds/bigsmoke/bs2.wav
sound/cl2/newsounds/bigsmoke/bs3.wav
sound/cl2/newsounds/bigsmoke/bs4.wav
sound/cl2/newsounds/bigsmoke/bs5.wav
sound/cl2/newsounds/bigsmoke/bs6.wav
sound/cl2/newsounds/boss_svoloch.wav
sound/cl2/newsounds/faggot1.wav
sound/cl2/newsounds/faggot2.wav
sound/cl2/newsounds/faggot3.wav
sound/cl2/newsounds/fail.wav
sound/cl2/newsounds/fuckyou.wav
sound/cl2/newsounds/job1.wav
sound/cl2/newsounds/job2.wav
sound/cl2/newsounds/lift.wav
sound/cl2/newsounds/lvl20speak1.wav
sound/cl2/newsounds/lvl20speak2.wav
sound/cl2/newsounds/lvl20speak3.wav
sound/cl2/newsounds/lvl20speak4.wav
sound/cl2/newsounds/lvl20speak5.wav
sound/cl2/newsounds/newba/newba1.wav
sound/cl2/newsounds/newba/newba2.wav
sound/cl2/newsounds/pressthebutton.wav
sound/cl2/newsounds/sci1.wav
sound/cl2/newsounds/sci2.wav
sound/cl2/newsounds/sci3.wav
sound/cl2/newsounds/sci4.wav
sound/cl2/newsounds/sci5.wav
sound/cl2/newsounds/sci6.wav
sound/cl2/newsounds/sci7.wav
sound/cl2/newsounds/scib1.wav
sound/cl2/newsounds/scib2.wav
sound/cl2/newsounds/scigas1.wav
sound/cl2/newsounds/scigas2.wav
sound/cl2/newsounds/scisuit.wav
sound/cl2/newsounds/stopthemusic.wav
sound/cl2/newsounds/story/ba1.wav
sound/cl2/newsounds/story/scic2.wav
sound/cl2/newsounds/story/scic3.wav
sound/cl2/newsounds/story/scid4.wav
sound/cl2/newsounds/story/scid5.wav
sound/cl2/newsounds/taunts/taunt1.wav
sound/cl2/newsounds/taunts/taunt2.wav
sound/cl2/newsounds/taunts/taunt3.wav
sound/cl2/newsounds/taunts/taunt4.wav
sound/cl2/newsounds/texttospeech.wav
sound/cl2/newsounds/tnt.wav
sound/cl2/newsounds/tr_dark.wav
sound/cl2/newsounds/wrongbutton.wav
