// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

gfx/env/motor_nightbk.tga
gfx/env/motor_nightdn.tga
gfx/env/motor_nightft.tga
gfx/env/motor_nightlf.tga
gfx/env/motor_nightrt.tga
gfx/env/motor_nightup.tga
models/hallohospital/m/blooder.mdl
models/hallohospital/m/crimson.mdl
models/hallohospital/m/ghostb.mdl
models/hallohospital/m/handcrab.mdl
models/hallohospital/m/hanger.mdl
models/hallohospital/m/rama.mdl
models/hallohospital/m/szombie.mdl
models/hallohospital/m/wheelchair_monster.mdl
models/hallohospital/m/zombie.mdl
models/hallohospital/m/zombie01.mdl
models/hallohospital/m/zombie02.mdl
models/hallohospital/m/zombie03.mdl
models/hallohospital/m/zombie_doctor.mdl
models/hallohospital/m/zombiet.mdl
models/hallohospital/m/zombika.mdl
models/hallohospital/p/arc_fern.mdl
models/hallohospital/p/bush_11.mdl
models/hallohospital/p/bush_12.mdl
models/hallohospital/p/pz_02.mdl
models/hallohospital/t/2chair.mdl
models/hallohospital/t/bench3.mdl
models/hallohospital/t/cafetable.mdl
models/hallohospital/t/desk.mdl
models/hallohospital/t/pissoir.mdl
models/hallohospital/t/pumpkin2.mdl
models/hallohospital/t/retyo.mdl
models/hallohospital/t/sofa.mdl
models/hallohospital/t/szek1.mdl
sound/halloween_hospital/3fbgm.wav
sound/halloween_hospital/birds9.wav
sound/halloween_hospital/breakthrough.wav
sound/halloween_hospital/buskrip.wav
sound/halloween_hospital/end1.wav
sound/halloween_hospital/end2.wav
sound/halloween_hospital/fosas.wav
sound/halloween_hospital/fosik.wav
sound/halloween_hospital/guit1.wav
sound/halloween_hospital/hhbgm.wav
sound/halloween_hospital/ki6.wav
sound/halloween_hospital/ki9.wav
sound/halloween_hospital/thankyou.wav
sound/halloween_hospital/vaggover.wav
sound/player/pl_wood_scr1.wav
sound/player/pl_wood_scr2.wav
sound/player/pl_wood_scr3.wav
sound/player/pl_wood_scr4.wav
