// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/neb6bk.tga
gfx/env/neb6dn.tga
gfx/env/neb6ft.tga
gfx/env/neb6lf.tga
gfx/env/neb6rt.tga
gfx/env/neb6up.tga
halflife.wad
liquids.wad
media/valve.mp3
models/common/lambda.mdl
sound/ambience/alien_beacon.wav
sound/ambience/alien_powernode.wav
sound/ambience/alien_purrmachine.wav
sound/ambience/alien_squit.wav
sound/ambience/alien_twow.wav
sound/ambience/aliencave1.wav
sound/ambience/alienvalve1.wav
sound/ambience/alienvalve2.wav
sound/ambience/alienwind1.wav
sound/ambience/computalk2.wav
sound/ambience/dronemachine1.wav
sound/ambience/dronemachine2.wav
sound/ambience/industrial2.wav
sound/ambience/labdrone2.wav
sound/ambience/mechwhine.wav
sound/ambience/particle_suck2.wav
sound/debris/beamstart1.wav
sound/debris/beamstart10.wav
sound/debris/beamstart7.wav
sound/debris/concrete1.wav
sound/nihilanth/nil_freeman.wav
sound/tentacle/te_sing1.wav
sound/tentacle/te_sing2.wav
sprites/blast.spr
sprites/fexplo1.spr
sprites/glow01.spr
sprites/glow02.spr
sprites/tele1.spr
sprites/xspark2.spr
sprites/yelflare2.spr
xeno.wad
