// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/alien3bk.tga
gfx/env/alien3dn.tga
gfx/env/alien3ft.tga
gfx/env/alien3lf.tga
gfx/env/alien3rt.tga
gfx/env/alien3up.tga
halflife.wad
media/valve.mp3
models/common/lambda.mdl
sound/ambience/alien_beacon.wav
sound/ambience/alien_builder.wav
sound/ambience/alien_creeper.wav
sound/ambience/alien_frantic.wav
sound/ambience/alien_powernode.wav
sound/ambience/alien_zonerator.wav
sound/ambience/aliencave1.wav
sound/ambience/alienfazzle1.wav
sound/ambience/alienvalve1.wav
sound/ambience/alienwind1.wav
sound/ambience/alienwind2.wav
sound/ambience/disgusting.wav
sound/ambience/dronemachine1.wav
sound/ambience/labgear.wav
sound/ambience/labmoan.wav
sound/ambience/particle_suck2.wav
sound/ambience/port_suckin1.wav
sound/ambience/port_suckout1.wav
sound/ambience/steamjet1.wav
sound/ambience/xtal_down1.wav
sound/ambience/zapmachine.wav
sound/debris/beamstart10.wav
sound/debris/beamstart5.wav
sound/debris/beamstart6.wav
sound/debris/beamstart7.wav
sound/debris/beamstart9.wav
sound/player/breathe2.wav
sound/player/heartbeat1.wav
sprites/fexplo1.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/tele1.spr
sprites/xsmoke1.spr
sprites/xspark2.spr
xeno.wad
