// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
halflife.wad
media/valve.mp3
models/common/lambda.mdl
sound/ambience/alien_cycletone.wav
sound/ambience/alien_minddrill.wav
sound/ambience/alien_powernode.wav
sound/ambience/alienfazzle1.wav
sound/ambience/alienlaser1.wav
sound/ambience/dronemachine1.wav
sound/ambience/labmoan.wav
sound/ambience/particle_suck2.wav
sound/ambience/port_suckin1.wav
sound/debris/beamstart10.wav
sound/debris/beamstart5.wav
sound/debris/beamstart6.wav
sound/debris/beamstart7.wav
sound/debris/beamstart9.wav
sound/nihilanth/nil_deceive.wav
sound/nihilanth/nil_done.wav
sound/nihilanth/nil_man_notman.wav
sound/nihilanth/nil_thelast.wav
sound/player/breathe1.wav
sprites/bexplo.spr
sprites/cexplo.spr
sprites/enter1.spr
sprites/exit1.spr
sprites/fexplo1.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/tele1.spr
sprites/zbeam1.spr
xeno.wad
