// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/xen8bk.tga
gfx/env/xen8dn.tga
gfx/env/xen8ft.tga
gfx/env/xen8lf.tga
gfx/env/xen8rt.tga
gfx/env/xen8up.tga
halflife.wad
media/valve.mp3
models/common/lambda.mdl
sound/ambience/alien_beacon.wav
sound/ambience/alien_builder.wav
sound/ambience/alien_creeper.wav
sound/ambience/alien_cycletone.wav
sound/ambience/alien_powernode.wav
sound/ambience/alien_squit.wav
sound/ambience/alien_twow.wav
sound/ambience/aliencave1.wav
sound/ambience/alienvoices1.wav
sound/ambience/alienwind2.wav
sound/ambience/computalk1.wav
sound/ambience/computalk2.wav
sound/ambience/dronemachine1.wav
sound/ambience/dronemachine2.wav
sound/ambience/labmoan.wav
sound/ambience/particle_suck2.wav
sound/ambience/port_suckin1.wav
sound/ambience/pounder.wav
sound/ambience/pulsemachine.wav
sound/ambience/squitch2.wav
sound/ambience/xtal_down1.wav
sound/barney/c1a4_ba_octo4.wav
sound/debris/beamstart14.wav
sound/debris/beamstart5.wav
sound/debris/beamstart7.wav
sound/debris/beamstart9.wav
sound/doors/aliendoor3.wav
sound/scientist/scream01.wav
sound/weapons/gauss2.wav
sprites/c-tele1.spr
sprites/fexplo1.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/tele1.spr
sprites/xspark2.spr
xeno.wad
