// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/nightbk.tga
gfx/env/nightdn.tga
gfx/env/nightft.tga
gfx/env/nightlf.tga
gfx/env/nightrt.tga
gfx/env/nightup.tga
halflife.wad
media/valve.mp3
models/common/lambda.mdl
sound/ambience/alien_beacon.wav
sound/ambience/alien_builder.wav
sound/ambience/alien_chatter.wav
sound/ambience/bigwarning.wav
sound/ambience/boomer.wav
sound/ambience/computalk1.wav
sound/ambience/computalk2.wav
sound/ambience/dronemachine1.wav
sound/ambience/dronemachine2.wav
sound/ambience/industrial2.wav
sound/ambience/industrial4.wav
sound/ambience/labdrone2.wav
sound/ambience/mechwhine.wav
sound/ambience/particle_suck1.wav
sound/ambience/particle_suck2.wav
sound/ambience/rocket_groan1.wav
sound/ambience/screammachine.wav
sound/ambience/steamjet1.wav
sound/ambience/techamb2.wav
sound/ambience/warn3.wav
sound/buttons/bell1.wav
sound/debris/beamstart2.wav
sound/debris/beamstart7.wav
sound/debris/beamstart9.wav
sound/vox/access.wav
sound/vox/detected.wav
sound/vox/unauthorized.wav
sound/weapons/mine_activate.wav
sprites/fexplo1.spr
sprites/flare3.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/tele1.spr
sprites/xsmoke1.spr
xeno.wad
