gfx/env/blood_bk.tga
gfx/env/blood_dn.tga
gfx/env/blood_ft.tga
gfx/env/blood_lf.tga
gfx/env/blood_rt.tga
gfx/env/blood_up.tga
maps/lavaking.gsr
maps/lavaking.res
models/lava/p_crowbar.mdl
models/lava/p_momslipper.mdl
models/lava/v_crowbar.mdl
models/lava/v_momslipper.mdl
models/lava/w_crowbar.mdl
models/lava/w_momslipper.mdl
models/lava/w_momslippert.mdl
scripts/maps/lava/common.as
scripts/maps/lava/momsreg.as
scripts/maps/lava/weapon_momslipper.as
sound/lava/cbar_hit1.wav
sound/lava/cbar_hit2.wav
sound/lava/cbar_miss1.wav
sound/lava/hit.wav
sound/lava/Turok2.mp3
sound/lava/weapons/cbar_hit1.wav
sound/lava/weapons/cbar_hit2.wav
sound/lava/weapons/cbar_hitbod1.wav
sound/lava/weapons/cbar_hitbod2.wav
sound/lava/weapons/cbar_hitbod3.wav
sound/lava/weapons/cbar_miss1.wav
sound/lava/weapons/lavaking.txt
sprites/eye.spr
sprites/moms/weapon_momslipper.txt
