maps/q2_custom_dm2.res
gfx/env/2desertusbkup.tga
gfx/env/2desertusbkdn.tga
gfx/env/2desertusbklf.tga
gfx/env/2desertusbkrt.tga
gfx/env/2desertusbkft.tga
gfx/env/2desertusbkbk.tga
sprites/glow01.spr
sprites/tele1.spr
sprites/laserbeam.spr
sprites/xenobeam.spr
sprites/redflare1.spr
sprites/red.spr
sound/weapons/shock_fire.wav
sound/stalkfire/rs/airplane2.wav
sound/stalkfire/rs/airplane3.wav
sound/stalkfire/rs/jetflyby1.wav
sound/ambience/jetflyby1.wav
sound/stalkfire/labgear.wav
sound/stalkfire/wpipes7.wav
sound/ambience/industrial1.wav
sound/stalkfire/ambience5.wav
sound/stalkfire/el_beam1.wav
sound/fans/fan1.wav
sound/stalkfire/electrichum.wav
sound/ambience/hammer.wav
sound/ambience/alienvoices1.wav
sprites/lgtning.spr
sound/ambience/alien_cycletone.wav
sprites/flare1.spr
sprites/xbeam3.spr
sprites/gwave1.spr