// TEXT
maps/quake2.gmr
maps/quake2.gsr

// WADS
quake2.wad

// SOUNDS //
sound/quake2/ammo.wav
sound/quake2/gib.wav
sound/quake2/item_q2armor1.wav
sound/quake2/item_q2armor2.wav
sound/quake2/item_q2health1.wav
sound/quake2/item_q2health2.wav
sound/quake2/item_q2health3.wav
sound/quake2/item_q2health4.wav
sound/quake2/ite_respawn.wav
sound/quake2/null.wav
sound/quake2/quad_activate.wav
sound/quake2/quad_fade.wav
sound/quake2/quad_fire.wav
sound/quake2/weapon.wav
sound/quake2/misc/talk.wav
sound/quake2/burn1.wav
sound/quake2/burn2.wav
sound/quake2/gasp1.wav
sound/quake2/gasp2.wav
sound/quake2/land1.wav
sound/quake2/step1.wav
sound/quake2/step2.wav
sound/quake2/step3.wav
sound/quake2/step4.wav
sound/quake2/water_in.wav
sound/quake2/water_out.wav
sound/quake2/water_under.wav
sound/quake2/male/bump1.wav
sound/quake2/male/death1.wav
sound/quake2/male/death2.wav
sound/quake2/male/death3.wav
sound/quake2/male/death4.wav
sound/quake2/male/drown1.wav
sound/quake2/male/fall1.wav
sound/quake2/male/fall1.wav
sound/quake2/male/gurp1.wav
sound/quake2/male/gurp2.wav
sound/quake2/male/jump1.wav
sound/quake2/male/pain25_1.wav
sound/quake2/male/pain25_2.wav
sound/quake2/male/pain50_1.wav
sound/quake2/male/pain50_2.wav
sound/quake2/male/pain75_1.wav
sound/quake2/male/pain75_2.wav
sound/quake2/male/pain100_1.wav
sound/quake2/male/pain100_2.wav
sound/quake2/female/bump1.wav
sound/quake2/female/death1.wav
sound/quake2/female/death2.wav
sound/quake2/female/death3.wav
sound/quake2/female/death4.wav
sound/quake2/female/drown1.wav
sound/quake2/female/fall1.wav
sound/quake2/female/fall2.wav
sound/quake2/female/gurp1.wav
sound/quake2/female/gurp2.wav
sound/quake2/female/jump1.wav
sound/quake2/female/pain25_1.wav
sound/quake2/female/pain25_2.wav
sound/quake2/female/pain50_1.wav
sound/quake2/female/pain50_2.wav
sound/quake2/female/pain75_1.wav
sound/quake2/female/pain75_2.wav
sound/quake2/female/pain100_1.wav
sound/quake2/female/pain100_2.wav
sound/quake2/cyborg/bump1.wav
sound/quake2/cyborg/death1.wav
sound/quake2/cyborg/death2.wav
sound/quake2/cyborg/death3.wav
sound/quake2/cyborg/death4.wav
sound/quake2/cyborg/drown1.wav
sound/quake2/cyborg/fall1.wav
sound/quake2/cyborg/fall2.wav
sound/quake2/cyborg/gurp1.wav
sound/quake2/cyborg/gurp2.wav
sound/quake2/cyborg/jump1.wav
sound/quake2/cyborg/pain25_1.wav
sound/quake2/cyborg/pain25_2.wav
sound/quake2/cyborg/pain50_1.wav
sound/quake2/cyborg/pain50_2.wav
sound/quake2/cyborg/pain75_1.wav
sound/quake2/cyborg/pain75_2.wav
sound/quake2/cyborg/pain100_1.wav
sound/quake2/cyborg/pain100_2.wav
// END SOUNDS //

// MODELS //
models/quake2/laser.mdl
models/quake2/p_bfg.mdl
models/quake2/p_blaster.mdl
models/quake2/p_blasterhd.mdl
models/quake2/p_chaingun.mdl
models/quake2/p_glauncher.mdl
models/quake2/p_grenade.mdl
models/quake2/p_hyperblaster.mdl
models/quake2/p_machinegun.mdl
models/quake2/p_railgun.mdl
models/quake2/p_railgunhd.mdl
models/quake2/p_rlauncher.mdl
models/quake2/p_shotgun.mdl
models/quake2/p_ssg.mdl
models/quake2/rocket.mdl
models/quake2/rockethd.mdl
models/quake2/v_bfg.mdl
models/quake2/v_blaster.mdl
models/quake2/v_blasterhd.mdl
models/quake2/v_chaingun.mdl
models/quake2/v_glauncher.mdl
models/quake2/v_grenade.mdl
models/quake2/v_hyperblaster.mdl
models/quake2/v_machinegun.mdl
models/quake2/v_railgun.mdl
models/quake2/v_railgunhd.mdl
models/quake2/v_rlauncher.mdl
models/quake2/v_shotgun.mdl
models/quake2/v_ssg.mdl
models/quake2/w_bfg.mdl
models/quake2/w_blaster.mdl
models/quake2/w_blasterhd.mdl
models/quake2/w_bullets.mdl
models/quake2/w_bulletshd.mdl
models/quake2/w_cells.mdl
models/quake2/w_cellshd.mdl
models/quake2/w_chain.mdl
models/quake2/w_chaingun.mdl
models/quake2/w_glauncher.mdl
models/quake2/w_grenade1.mdl
models/quake2/w_grenade2.mdl
models/quake2/w_grenades.mdl
models/quake2/w_grenadeshd.mdl
models/quake2/w_hyperblaster.mdl
models/quake2/w_machinegun.mdl
models/quake2/w_q2armor1.mdl
models/quake2/w_q2armor2.mdl
models/quake2/w_q2armor3.mdl
models/quake2/w_q2armor4.mdl
models/quake2/w_q2health1.mdl
models/quake2/w_q2health2.mdl
models/quake2/w_q2health3.mdl
models/quake2/w_q2health4.mdl
models/quake2/w_quad.mdl
models/quake2/w_quadhd.mdl
models/quake2/w_railgun.mdl
models/quake2/w_railgunhd.mdl
models/quake2/w_rlauncher.mdl
models/quake2/w_rockets.mdl
models/quake2/w_rocketshd.mdl
models/quake2/w_shell_mg.mdl
models/quake2/w_shell_sg.mdl
models/quake2/w_shells.mdl
models/quake2/w_shellshd.mdl
models/quake2/w_shotgun.mdl
models/quake2/w_slugs.mdl
models/quake2/w_slugshd.mdl
models/quake2/w_ssg.mdl
// END MODELS //

// SPRITES //
sprites/quake2/ammo.spr
sprites/quake2/bfg_beam.spr
sprites/quake2/bfg_explosion.spr
sprites/quake2/bfg_icon.spr
sprites/quake2/bfg_particle.spr
sprites/quake2/bfg_sprite.spr
sprites/quake2/blaster_icon.spr
sprites/quake2/cg_icon.spr
sprites/quake2/gl_icon.spr
sprites/quake2/hb_icon.spr
sprites/quake2/hg_icon.spr
sprites/quake2/icninvin.spr
sprites/quake2/icninvis.spr
sprites/quake2/mg_icon.spr
sprites/quake2/phanlanx_icon.spr
sprites/quake2/rg_icon.spr
sprites/quake2/ripper_icon.spr
sprites/quake2/rl_icon.spr
sprites/quake2/sg_icon.spr
sprites/quake2/ssg_icon.spr
sprites/quake2/weapons/weapon_q2b.txt
sprites/quake2/weapons/weapon_q2bfg.txt
sprites/quake2/weapons/weapon_q2blaster.txt
sprites/quake2/weapons/weapon_q2cg.txt
sprites/quake2/weapons/weapon_q2chaingun.txt
sprites/quake2/weapons/weapon_q2gl.txt
sprites/quake2/weapons/weapon_q2glauncher.txt
sprites/quake2/weapons/weapon_q2grenade.txt
sprites/quake2/weapons/weapon_q2hb.txt
sprites/quake2/weapons/weapon_q2hg.txt
sprites/quake2/weapons/weapon_q2hyperblaster.txt
sprites/quake2/weapons/weapon_q2machinegun.txt
sprites/quake2/weapons/weapon_q2mg.txt
sprites/quake2/weapons/weapon_q2railgun.txt
sprites/quake2/weapons/weapon_q2rg.txt
sprites/quake2/weapons/weapon_q2rl.txt
sprites/quake2/weapons/weapon_q2rlauncher.txt
sprites/quake2/weapons/weapon_q2sg.txt
sprites/quake2/weapons/weapon_q2shotgun.txt
sprites/quake2/weapons/weapon_q2ssg.txt
sprites/quake2/weapons/weapon_q2supershotgun.txt
// END SPRITES //
