// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/keenhalloween/cryokeen.mdl
models/scmod/npcs/massn/keen.mdl
models/scmod/npcs/rgrunt/turrican.mdl
models/scmod/reddeath/hopper.mdl
models/scmod/reddeath/megaturrican.mdl
models/scmod/reddeath/nomble.mdl
models/scmod/reddeath/shadowchild.mdl
models/scmod/reddeath/superturrican.mdl
models/scmod/reddeath/turrible.mdl
models/scmod/secretcity/redslime.mdl
models/scmod/weapons/dmc/b_nail1.mdl
models/scmod/weapons/dmc/b_nail1t.mdl
models/scmod/weapons/dmc/light/p_shock.mdl
models/scmod/weapons/dmc/light/v_shock.mdl
models/scmod/weapons/dmc/light/w_shock.mdl
models/scmod/weapons/dmc/light/w_shock_rifle.mdl
models/scmod/weapons/dmc/ngun2/p_9mmar.mdl
models/scmod/weapons/dmc/ngun2/v_9mmar.mdl
models/scmod/weapons/dmc/ngun2/w_9mmar.mdl
models/scmod/weapons/dmc/shot/p_shotgun.mdl
models/scmod/weapons/dmc/shot/v_shotgun.mdl
models/scmod/weapons/dmc/shot/w_shotgun.mdl
models/scmod/weapons/dmc/w_battery.mdl
models/scmod/weapons/dmc/w_batteryt.mdl
models/scmod/weapons/dmc/w_shotbox.mdl
models/scmod/weapons/dmc/w_shotboxt.mdl
models/turr/intruder2.mdl
sound/keenhalloween/fuzz.wav
sound/scmod/reddeath/credits.ogg
sound/scmod/reddeath/dialogs/10turrican_r.ogg
sound/scmod/reddeath/dialogs/11keen_r.ogg
sound/scmod/reddeath/dialogs/12turrican_r.ogg
sound/scmod/reddeath/dialogs/13turrican_e.ogg
sound/scmod/reddeath/dialogs/14keen_r.ogg
sound/scmod/reddeath/dialogs/15turrican_e.ogg
sound/scmod/reddeath/dialogs/16keen_r.ogg
sound/scmod/reddeath/dialogs/17keen.ogg
sound/scmod/reddeath/dialogs/1turrican.ogg
sound/scmod/reddeath/dialogs/2turrican.ogg
sound/scmod/reddeath/dialogs/3turrican.ogg
sound/scmod/reddeath/dialogs/4keen.ogg
sound/scmod/reddeath/dialogs/5turrican.ogg
sound/scmod/reddeath/dialogs/6keen.ogg
sound/scmod/reddeath/dialogs/7turrican.ogg
sound/scmod/reddeath/dialogs/8turrican_r.ogg
sound/scmod/reddeath/dialogs/9turrican_r.ogg
sound/scmod/reddeath/dialogs/turrican_coming.ogg
sound/scmod/reddeath/lairstart.ogg
sound/scmod/reddeath/nombleboss.ogg
sound/scmod/reddeath/nombleboss_intro.ogg
sound/scmod/reddeath/shadowsattack.ogg
sound/scmod/reddeath/shipcrash.ogg
sound/scmod/reddeath/turriblefight.ogg
sound/scmod/reddeath/turriblefight_intro.ogg
sound/sp_portal/quake3.wav
sound/tur/creepy1.wav
sound/tur/creepy2.wav
sound/tur/creepy3.wav
sound/tur/creepy4.wav
sound/tur/creepy5.wav
sound/tur/riker.wav
sound/weapons/dmc/light/lstart.wav
sound/weapons/dmc/ngun2/spike2.wav
sound/weapons/dmc/shot/guncock.wav
sound/weapons/dmc/weapon.wav
