// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/merryxmas/ownage.mdl
models/merryxmas/xms_beartoy.mdl
models/merryxmas/xms_bush.mdl
models/merryxmas/xms_cane.mdl
models/merryxmas/xms_duke.mdl
models/merryxmas/xms_grass.mdl
models/merryxmas/xms_hat1.mdl
models/merryxmas/xms_hat4.mdl
models/merryxmas/xms_hat5.mdl
models/merryxmas/xms_hat6.mdl
models/merryxmas/xms_hp1.mdl
models/merryxmas/xms_present1.mdl
models/merryxmas/xms_present2.mdl
models/merryxmas/xms_present3.mdl
models/merryxmas/xms_xmastree.mdl
models/player/pedobear/pedobear.bmp
models/player/pedobear/pedobear.mdl
models/santas_workshop/ball.mdl
models/santas_workshop/dinotoy.mdl
models/santas_workshop/mus_beer.mdl
models/santas_workshop/mus_chair.mdl
models/santas_workshop/mus_sofa.mdl
models/santas_workshop/playstation.mdl
models/santas_workshop/puki1.mdl
models/santas_workshop/puki2.mdl
models/santas_workshop/sledges.mdl
models/santas_workshop/snowtree1.mdl
models/santas_workshop/tigertoy.mdl
models/santas_workshop/toygun.mdl
models/santas_workshop/v_crowbar.mdl
models/santas_workshop/xmstreebig.mdl
sound/merryxmas/xms_fart.wav
sound/merryxmas/xms_radio6.ogg
sound/merryxmas/xms_radio7.ogg
sound/santas_workshop/amb_firebig.wav
sound/santas_workshop/beer.wav
sound/santas_workshop/boss.ogg
sound/santas_workshop/eg_gasp.wav
sound/santas_workshop/gzfolks.wav
sound/santas_workshop/gzfolks3.wav
sound/santas_workshop/lasers.wav
sound/santas_workshop/laugh.wav
sound/santas_workshop/music00.ogg
sound/santas_workshop/music01.ogg
sound/santas_workshop/music02.ogg
sound/santas_workshop/powerup.wav
sprites/santas_workshop/flames.spr
sprites/santas_workshop/glow1.spr
sprites/santas_workshop/greenhud.spr
sprites/santas_workshop/greenteam.spr
sprites/santas_workshop/laser_beam.spr
sprites/santas_workshop/laser_glow.spr
sprites/santas_workshop/lightning.spr
sprites/santas_workshop/steam2.spr
sprites/santas_workshop/yellhud.spr
sprites/santas_workshop/yellteam.spr
