// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/merryxmas/xms_crabhat.mdl
models/merryxmas/xms_hat1.mdl
models/merryxmas/xms_hat2.mdl
models/merryxmas/xms_hat3.mdl
models/merryxmas/xms_hat4.mdl
models/merryxmas/xms_hat5.mdl
models/merryxmas/xms_rat.mdl
models/merryxmas/xms_xmastree.mdl
models/player/pedobear/pedobear.bmp
models/player/pedobear/pedobear.mdl
models/santas_workshop/idcard.mdl
models/santas_workshop/larry.mdl
models/santas_workshop/v_crowbar.mdl
sound/merryxmas/xms_radio1.ogg
sound/merryxmas/xms_radio2.ogg
sound/merryxmas/xms_radio3.ogg
sound/merryxmas/xms_radio4.ogg
sound/merryxmas/xms_radio5.ogg
sound/santas_workshop/announcer.wav
sound/santas_workshop/burb.wav
sound/santas_workshop/conv.wav
sound/santas_workshop/endfloor.wav
sound/santas_workshop/gzfolks.wav
sound/santas_workshop/gzfolks2.wav
sound/santas_workshop/intro.ogg
sound/santas_workshop/lasers.wav
sound/santas_workshop/pipe.wav
sound/santas_workshop/sound_done.wav
sound/santas_workshop/steam.wav
sound/santas_workshop/storage.wav
sound/santas_workshop/xms_hoho.wav
sprites/santas_workshop/greenhud.spr
sprites/santas_workshop/greenteam.spr
sprites/santas_workshop/laser_beam.spr
sprites/santas_workshop/laser_glow.spr
sprites/santas_workshop/smoke.spr
sprites/santas_workshop/yellhud.spr
sprites/santas_workshop/yellteam.spr
