models/sc_cyclone/apc.mdl
models/sc_cyclone/Truckrussian.mdl
models/sc_cyclone/audi80.mdl
models/sc_cyclone/bil1.mdl
models/sc_cyclone/hevcharge_wall.mdl
models/sc_cyclone/medkit_wall.mdl
models/sc_cyclone/baby_voltigore_pink.mdl
sound/sc_cyclone/blue.ogg
sound/sc_cyclone/buttonpower.wav
sound/sc_cyclone/buzzer_pipe1.wav
sound/sc_cyclone/buzzer_wind3.wav
sound/sc_cyclone/cat.wav
sound/sc_cyclone/comp3.wav
sound/sc_cyclone/computer_beeps.wav
sound/sc_cyclone/Explo_metal01.wav
sound/sc_cyclone/grate_close.wav
sound/sc_cyclone/high_wind1.wav
sound/sc_cyclone/moveon.wav
sound/sc_cyclone/objecdone.wav
sound/sc_cyclone/securityalarm.wav
sprites/sc_cyclone/prok.spr
maps/sc_cyclone.cfg
maps/sc_cyclone_motd.txt
maps/sc_cyclone.res
sc_cyclone.wad
gfx/env/mountainpassft.bmp
gfx/env/mountainpasslf.bmp
gfx/env/mountainpassrt.bmp
gfx/env/mountainpassup.bmp
gfx/env/mountainpassdn.bmp
gfx/env/mountainpassbk.bmp
maps/sc_cyclone.gmr
maps/sc_cyclone.gsr