// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/sectore/cryogrunt.mdl
models/sectore/darkdrone3.mdl
models/sectore/freeman.mdl
sound/sectore/341422_Iysis__HighTreson_.mp3
sound/sectore/alienmessage2.wav
sound/sectore/battleofsteel.xm
sound/sectore/doompickup.wav
sound/sectore/flowerget.wav
sound/sectore/gman_cya.wav
sound/sectore/hks1.wav
sound/sectore/hks2.wav
sound/sectore/hks3.wav
sound/sectore/hlcoolmusic_once.mp3
sound/sectore/laber.mod
sound/sectore/labrece.mod
sound/sectore/pit_drone_alert1.wav
sound/sectore/pit_drone_alert2.wav
sound/sectore/pit_drone_alert3.wav
sound/sectore/pit_drone_attack_spike1.wav
sound/sectore/pit_drone_attack_spike2.wav
sound/sectore/pit_drone_communicate1.wav
sound/sectore/pit_drone_communicate2.wav
sound/sectore/pit_drone_communicate3.wav
sound/sectore/pit_drone_communicate4.wav
sound/sectore/pit_drone_die1.wav
sound/sectore/pit_drone_die2.wav
sound/sectore/pit_drone_die3.wav
sound/sectore/pit_drone_eat.wav
sound/sectore/pit_drone_hunt1.wav
sound/sectore/pit_drone_hunt2.wav
sound/sectore/pit_drone_hunt3.wav
sound/sectore/pit_drone_idle1.wav
sound/sectore/pit_drone_idle2.wav
sound/sectore/pit_drone_idle3.wav
sound/sectore/pit_drone_melee_attack1.wav
sound/sectore/pit_drone_melee_attack2.wav
sound/sectore/pit_drone_pain1.wav
sound/sectore/pit_drone_pain2.wav
sound/sectore/pit_drone_pain3.wav
sound/sectore/pit_drone_pain4.wav
sound/sectore/pl_gun1.wav
sound/sectore/pl_gun2.wav
sound/sectore/pl_gun3.wav
sound/sectore/teleport.wav
sound/sectore/xenop4music_once.mp3
sound/sectore_3/allflowers.wav
sprites/flower.spr
