// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/sectore/cryogrunt.mdl
models/sectore/darkdrone3.mdl
models/sectore/glassdrone.mdl
models/sectore/player/cryokeen/cryokeen.mdl
sound/sectore/alienmessage.wav
sound/sectore/boss.wav
sound/sectore/burn.wav
sound/sectore/doompickup.wav
sound/sectore/elevatorrise.wav
sound/sectore/flowerget.wav
sound/sectore/gruntchat_once.mp3
sound/sectore/hks1.wav
sound/sectore/hks2.wav
sound/sectore/hks3.wav
sound/sectore/jetout.wav
sound/sectore/pit_drone_alert1.wav
sound/sectore/pit_drone_alert2.wav
sound/sectore/pit_drone_alert3.wav
sound/sectore/pit_drone_attack_spike1.wav
sound/sectore/pit_drone_attack_spike2.wav
sound/sectore/pit_drone_communicate1.wav
sound/sectore/pit_drone_communicate2.wav
sound/sectore/pit_drone_communicate3.wav
sound/sectore/pit_drone_communicate4.wav
sound/sectore/pit_drone_die1.wav
sound/sectore/pit_drone_die2.wav
sound/sectore/pit_drone_die3.wav
sound/sectore/pit_drone_eat.wav
sound/sectore/pit_drone_hunt1.wav
sound/sectore/pit_drone_hunt2.wav
sound/sectore/pit_drone_hunt3.wav
sound/sectore/pit_drone_idle1.wav
sound/sectore/pit_drone_idle2.wav
sound/sectore/pit_drone_idle3.wav
sound/sectore/pit_drone_melee_attack1.wav
sound/sectore/pit_drone_melee_attack2.wav
sound/sectore/pit_drone_pain1.wav
sound/sectore/pit_drone_pain2.wav
sound/sectore/pit_drone_pain3.wav
sound/sectore/pit_drone_pain4.wav
sound/sectore/pl_gun1.wav
sound/sectore/pl_gun2.wav
sound/sectore/pl_gun3.wav
sound/sectore/shieldoff.wav
sound/sectore/spaceambient.wav
sound/sectore/supb.wav
sound/sectore/teleport.wav
sprites/flower.spr
