// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/sectore/darkdrone3.mdl
models/sectore/gordon.mdl
models/sectore/panther.mdl
models/sectore/panther01.mdl
sound/sectore/278161_Gravitational_Pull_2_.mp3
sound/sectore/83257-space_walk.mod
sound/sectore/captured.s3m
sound/sectore/doompickup.wav
sound/sectore/dust_raiders.mod
sound/sectore/eleup.wav
sound/sectore/eleup2.wav
sound/sectore/elevatormusic.wav
sound/sectore/elevatorrise.wav
sound/sectore/flowerget.wav
sound/sectore/goodwork.wav
sound/sectore/hks1.wav
sound/sectore/hks2.wav
sound/sectore/hks3.wav
sound/sectore/jazz_jackrabbit_2_-_labratory_level.s3m
sound/sectore/p_alert1.wav
sound/sectore/p_alert2.wav
sound/sectore/p_alert3.wav
sound/sectore/p_die1.wav
sound/sectore/p_idle1.wav
sound/sectore/p_idle2.wav
sound/sectore/p_idle3.wav
sound/sectore/p_pain1.wav
sound/sectore/p_pain2.wav
sound/sectore/pit_drone_alert1.wav
sound/sectore/pit_drone_alert2.wav
sound/sectore/pit_drone_alert3.wav
sound/sectore/pit_drone_attack_spike1.wav
sound/sectore/pit_drone_attack_spike2.wav
sound/sectore/pit_drone_communicate1.wav
sound/sectore/pit_drone_communicate2.wav
sound/sectore/pit_drone_communicate3.wav
sound/sectore/pit_drone_communicate4.wav
sound/sectore/pit_drone_die1.wav
sound/sectore/pit_drone_die2.wav
sound/sectore/pit_drone_die3.wav
sound/sectore/pit_drone_eat.wav
sound/sectore/pit_drone_hunt1.wav
sound/sectore/pit_drone_hunt2.wav
sound/sectore/pit_drone_hunt3.wav
sound/sectore/pit_drone_idle1.wav
sound/sectore/pit_drone_idle2.wav
sound/sectore/pit_drone_idle3.wav
sound/sectore/pit_drone_melee_attack1.wav
sound/sectore/pit_drone_melee_attack2.wav
sound/sectore/pit_drone_pain1.wav
sound/sectore/pit_drone_pain2.wav
sound/sectore/pit_drone_pain3.wav
sound/sectore/pit_drone_pain4.wav
sound/sectore/pl_gun1.wav
sound/sectore/pl_gun2.wav
sound/sectore/pl_gun3.wav
sound/sectore/screamweird.wav
sound/sectore/screamweird2.wav
sound/sectore/shieldoff.wav
sprites/flower.spr
