// tdm_classicdawn.res - created with RESGen v2.0.3.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (57):
decals.wad
dmc.wad
febbsmedika/dm_invis.spr
febbsmedika/dm_invul.spr
febbsmedika/dm_quaddmg.spr
febcdawn.wad
gfx/env/de_stormbk.tga
gfx/env/de_stormdn.tga
gfx/env/de_stormft.tga
gfx/env/de_stormlf.tga
gfx/env/de_stormrt.tga
gfx/env/de_stormup.tga
halflife.wad
lcd_display.wad
liquids.wad
models/febbsmedika/pow_invis_anim.mdl
models/febbsmedika/pow_invuln_anim.mdl
models/febbsmedika/pow_quad_anim.mdl
models/player/dmhelmet_blue/dmhelmet_blue.mdl
models/player/dmhelmet_red/dmhelmet_red.mdl
Opfor.wad
sound/ambience/alien_creeper.wav
sound/ambience/alien_minddrill.wav
sound/ambience/computalk1.wav
sound/ambience/drips.wav
sound/ambience/fluorescent.wav
sound/ambience/rocket_groan1.wav
sound/ambience/water_flowing2.wav
sound/ambience/waterrun.wav
sound/febbsmedika/arena_music.wav
sound/febbsmedika/Birds9.wav
sound/febbsmedika/ending_sting.wav
sound/febbsmedika/febbshealingpool1.wav
sound/febbsmedika/healthchargeloop.wav
sound/febbsmedika/healthchargeno.wav
sound/febbsmedika/healthchargeyes.wav
sound/febbsmedika/hevchargeloop.wav
sound/febbsmedika/hevchargeno.wav
sound/febbsmedika/hevchargeyes.wav
sound/febbsmedika/invis.wav
sound/febbsmedika/invis_wearout.wav
sound/febbsmedika/invul.wav
sound/febbsmedika/invul_wearout.wav
sound/febbsmedika/invul_wearout_oneshot.wav
sound/febbsmedika/lobby_music.wav
sound/febbsmedika/monikaradio1.wav
sound/febbsmedika/quaddmg.wav
sound/febbsmedika/quaddmg_wearout.wav
sound/febbsmedika/quaddmg_wearout_oneshot.wav
sound/febbsmedika/randtelesound.wav
sound/febbsmedika/slipgate1.wav
sprites/b-tele1.spr
sprites/e-tele1.spr
sprites/xspark2.spr
tfc.WAD
tfc2.wad
xeno.wad

sound/rng/deluge/weapons/car_bolt.ogg
sound/rng/deluge/weapons/car_clipin.ogg
sound/rng/deluge/weapons/car_clipout.ogg
sound/rng/deluge/weapons/car_draw.ogg
sound/rng/deluge/weapons_v3/car_fire.ogg
sound/rng/deluge/weapons/gundor_draw.ogg
sound/rng/deluge/weapons/gundor_fire.wav
sound/rng/deluge/weapons/gundor_idle.ogg
sound/rng/deluge/weapons/gundor_off.ogg
sound/rng/deluge/weapons/gundor_on.ogg
sound/rng/deluge/weapons/mag_clipin.ogg
sound/rng/deluge/weapons/mag_clipout.ogg
sound/rng/deluge/weapons/mag_draw.ogg
sound/rng/deluge/weapons_v3/mag_fire.ogg
sound/rng/deluge/weapons/mag_slide.ogg
sound/rng/deluge/weapons/mgun_ammobelt.ogg
sound/rng/deluge/weapons/mgun_ammobeltoff.ogg
sound/rng/deluge/weapons/mgun_bolt.ogg
sound/rng/deluge/weapons/mgun_clipin.ogg
sound/rng/deluge/weapons/mgun_clipout.ogg
sound/rng/deluge/weapons/mgun_close.ogg
sound/rng/deluge/weapons/mgun_draw.ogg
sound/rng/deluge/weapons_v3/mgun_fire.ogg
sound/rng/deluge/weapons/mgun_open.ogg
sound/rng/deluge/weapons/propulsion_draw.ogg
sound/rng/deluge/weapons_v3/propulsion_fire.ogg
sound/rng/deluge/weapons_v3/propulsion_fire2.ogg
sound/rng/deluge/weapons/propulsion_spin.ogg
sound/rng/deluge/weapons/propulsion_spinup.ogg
sound/rng/deluge/weapons/propulsion_zap1.ogg
sound/rng/deluge/weapons/propulsion_zap2.ogg
sound/rng/deluge/weapons/propulsion_zap3.ogg
sound/rng/deluge/weapons/rifle_bolt.ogg
sound/rng/deluge/weapons/rifle_clipin.ogg
sound/rng/deluge/weapons/rifle_clipout.ogg
sound/rng/deluge/weapons/rifle_draw.ogg
sound/rng/deluge/weapons_v3/rifle_fire.ogg
sound/rng/deluge/weapons/shotgun_draw.ogg
sound/rng/deluge/weapons_v3/shotgun_fire.ogg
sound/rng/deluge/weapons_v3/shotgun_fire2.ogg
sound/rng/deluge/weapons/shotgun_reload.ogg
sound/rng/deluge/weapons/smg_clipin.ogg
sound/rng/deluge/weapons/smg_clipout.ogg
sound/rng/deluge/weapons/smg_draw.ogg
sound/rng/deluge/weapons_v3/smg_fire.ogg
sound/rng/deluge/weapons/steampipe_draw.ogg
sound/rng/deluge/weapons/steampipe_hit.ogg
sound/rng/deluge/weapons/steampipe_hitflesh.ogg
sound/rng/deluge/weapons/steampipe_swing.ogg
sound/rng/deluge/weapons/vp_pistol_clipin.ogg
sound/rng/deluge/weapons/vp_pistol_clipout.ogg
sound/rng/deluge/weapons/vp_pistol_draw.ogg
sound/rng/deluge/weapons_v3/vp_pistol_fire.ogg
sound/rng/deluge/weapons_v3/vp_pistol_fire_empty.ogg
sound/rng/deluge/weapons/vp_pistol_slide.ogg
sound/rng/deluge/weapons/punch_miss.ogg
sound/rng/deluge/weapons/punch_hit.ogg
sound/rng/deluge/weapons/punch_hitbody.ogg
sound/rng/deluge/weapons/kick_miss.ogg
sound/rng/deluge/weapons/kick_hit.ogg
sound/rng/deluge/weapons/kick_hitbody.ogg
sound/rng/deluge/weapons/fists_draw.ogg


models/rngstuff/deluge_beta/weapons_v3/v_pistol.mdl
models/rngstuff/deluge_beta/weapons/w_pistol.mdl
models/rngstuff/deluge_beta/weapons/p_pistol.mdl
models/rngstuff/deluge_beta/weapons_v3/v_carbine.mdl
models/rngstuff/deluge_beta/weapons/w_carbine.mdl
models/rngstuff/deluge_beta/weapons/p_carbine.mdl
models/rngstuff/deluge_beta/weapons_v3/v_smg.mdl
models/rngstuff/deluge_beta/weapons/w_smg.mdl
models/rngstuff/deluge_beta/weapons/p_smg.mdl
models/rngstuff/deluge_beta/weapons/v_steampipe.mdl
models/rngstuff/deluge_beta/weapons/w_steampipe.mdl
models/rngstuff/deluge_beta/weapons/p_steampipe.mdl
models/rngstuff/deluge_beta/weapons_v3/v_scattergun.mdl
models/rngstuff/deluge_beta/weapons/w_scattergun.mdl
models/rngstuff/deluge_beta/weapons/p_scattergun.mdl
models/rngstuff/deluge_beta/weapons_v3/v_magnum.mdl
models/rngstuff/deluge_beta/weapons/w_magnum.mdl
models/rngstuff/deluge_beta/weapons/p_magnum.mdl
models/rngstuff/deluge_beta/weapons_v3/v_machinegun.mdl
models/rngstuff/deluge_beta/weapons/w_machinegun.mdl
models/rngstuff/deluge_beta/weapons/p_machinegun.mdl
models/rngstuff/deluge_beta/weapons_v3/v_propulsion.mdl
models/rngstuff/deluge_beta/weapons/w_propulsion.mdl
models/rngstuff/deluge_beta/weapons/p_propulsion.mdl
models/rngstuff/deluge_beta/weapons_v3/v_rifle.mdl
models/rngstuff/deluge_beta/weapons/w_rifle.mdl
models/rngstuff/deluge_beta/weapons/p_rifle.mdl
models/rngstuff/deluge_beta/weapons/v_gundor.mdl
models/rngstuff/deluge_beta/weapons/w_gundor.mdl
models/rngstuff/deluge_beta/weapons/p_gundor.mdl
models/rngstuff/deluge_beta/weapons/v_fists.mdl
models/rngstuff/deluge_beta/weapons/p_fists.mdl

